### ISSUE TITLE
Adaptive bezier subdivision

### ISSUE THREAD

**Issue by schell** [kuribas/cubicbezier#2]
I'd like to implement adaptive bezier subdivision as explained in http://www.antigrain.com/research/adaptive_bezier/index.html. Since I'm new to your library - what's the easiest way to determine if a "curve is flat"?

**Comment by kuribas** [comment]
You can use `colinear` which tests if the curve falls within a line of the given thickness.

**Comment by schell** [comment]
Thanks @kuribas - I ended up implementing it myself. I'll close this out now.
