### ISSUE TITLE
Test suite compilation failure

### ISSUE THREAD

**Issue by snoyberg** [kuribas/cubicbezier#3]
```
Preprocessing test suite 'test' for cubicbezier-0.4.0.2...
[1 of 1] Compiling Main             ( tests/test.hs, dist/build/test/test-tmp/Main.o )

tests/test.hs:8:1: error:
    Failed to load interface for ‘MPTest’
    Use -v to see a list of the files searched for.

tests/test.hs:9:1: error:
    Failed to load interface for ‘NumTest’
    Use -v to see a list of the files searched for.
```

**Comment by byorgey** [comment]
@kuribas , where are these files `MPTest` and `NumTest`?  I do not see them in the repository anywhere.  But clearly they are needed since if I try deleting those imports from `test.hs` I get a bunch of "not in scope" errors.

**Comment by kuribas** [comment]
Sorry, the testsuite was broken.

**Comment by snoyberg** [comment]
Can you ping this issue or the Stackage issue tracker when a new version is
on Hackage?
