### ISSUE TITLE
Hackage 0.6.0.3 does not include commit text fixes

### ISSUE THREAD

**Issue by rybern** [kuribas/cubicbezier#7]
The [latest version on Hackage](https://hackage.haskell.org/package/cubicbezier-0.6.0.3) does not include [this commit](https://github.com/kuribas/cubicbezier/commit/6b3faf38c61fa71164246535b62131bda67a5521), which made tests compile. So the Hackage version does not compile for me. Please upload the latest version to Hackage.

Thanks!

**Comment by kuribas** [comment]
fixed with 0.6.0.4
